Print count of orphaned tasks and orphaned task locks in the log mess…
linkedin/brooklin pull request #844
Opened 2021-07-28 22:23 UTC by surajkn

…age in addition to

the actual tasks/locks and connector info.

Important: DO NOT REPORT SECURITY ISSUES DIRECTLY ON GITHUB.  
For reporting security issues and contributing security fixes,  
please, email security@linkedin.com instead, as described in  
the contribution guidelines.

Please, take a minute to review the contribution guidelines at:  
https://github.com/linkedin/Brooklin/blob/master/CONTRIBUTING.md

2021-07-28 22:56 UTC, vmaheshw requested changes
Fix the description of the PR.

2021-08-03 05:47 UTC, vmaheshw commented on datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java
> +        LOG.warn("Found {} number of orphan tasks: {} in connector: {}", connectorTaskList.size(),
nit pick: `Found 10 number of orphan task` does not sound right. How about `Found 10 orphan tasks:`?

2021-08-03 05:47 UTC, vmaheshw commented on datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java
> +        LOG.warn("Found {} number of orphan task locks: {} in connector: {}", orphanLockList.size(),
same as above comment.

2021-08-04 18:00 UTC, shrinandthakkar approved these changes

2021-08-06 05:45 UTC, vmaheshw approved these changes
LGTM

2021-08-10 06:12 UTC, merged