Upgrade Pre Assignment Clean Up To Remove Dependency Tasks Across Hosts
linkedin/brooklin pull request #952
Opened 2023-08-14 19:10 UTC by shrinandthakkar

## Summary
- When a newly elected leader receives an instance-task assignment from ZK, it is expected that the leader will perform a cleanup routine on the assignment. Failure to do so may lead to inconsistencies in task assignment across instances.
- At present, the pre-assignment cleanup only checks for dependency tasks in the current host's assignment and cleans them up accordingly. This process does not extend to other hosts, meaning that if the same task (a dependency list task) is assigned to another host, due to any unforeseen circumstances, it will not be cleaned up.
- This is not a bug, rather it is a safety measure to restore the assignments in the event of a new leader being elected following a bad task assignment.

___

Important: DO NOT REPORT SECURITY ISSUES DIRECTLY ON GITHUB.  
For reporting security issues and contributing security fixes,  
please, email security@linkedin.com instead, as described in  
the contribution guidelines.

Please, take a minute to review the contribution guidelines at:  
https://github.com/linkedin/Brooklin/blob/master/CONTRIBUTING.md

2023-08-15 19:19 UTC, ehoner requested changes

2023-08-15 20:43 UTC, shrinandthakkar commented on datastream-server/src/main/java/com/linkedin/datastream/server/assignment/StickyPartitionAssignmentStrategy.java
> +        .map(task -> ((DatastreamTaskImpl) task).getDependencies())
done

2023-08-15 20:43 UTC, shrinandthakkar commented on datastream-server/src/test/java/com/linkedin/datastream/server/assignment/TestStickyPartitionAssignmentStrategy.java
> +    List<DatastreamGroup> datastreams = generateDatastreams("testTasksCleanUpWithDuplicatesAcrossInstances", 1, 3);
the var to be used in streams api lambda needs to be final. Hence created a new var.

2023-08-15 20:43 UTC, shrinandthakkar commented on datastream-server/src/test/java/com/linkedin/datastream/server/assignment/TestStickyPartitionAssignmentStrategy.java
> +    Map<String, Set<DatastreamTask>> finalAssignment = assignment;
the var to be used in streams api lambda needs to be final. Hence created a new var.

2023-08-15 21:08 UTC, ehoner commented on datastream-server/src/test/java/com/linkedin/datastream/server/assignment/TestStickyPartitionAssignmentStrategy.java
> +    Map<String, Set<DatastreamTask>> finalAssignment = assignment;
thanks. I missed that.

2023-08-15 21:08 UTC, ehoner approved these changes

2023-08-29 19:32 UTC, hshukla approved these changes

2023-08-29 19:33 UTC, merged